# Generated by Django 3.2.8 on 2021-11-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodocente',
            options={'verbose_name': 'No Docente', 'verbose_name_plural': 'No Docentes'},
        ),
    ]
