# Generated by Django 3.2.8 on 2021-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_docente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodocente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen'),
        ),
    ]
